kind: Deployment
apiVersion: apps/v1
metadata:
  name: nextcloud-apache
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.nextcloud.replicas }}
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
        - name: nextcloud
          image: "{{ .Values.nextcloud.image }}:{{ .Values.nextcloud.tag }}" 
          imagePullPolicy: {{ .Values.nextcloud.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: NEXTCLOUD_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: nextcloud-secrets
                  key: nextcloud_admin_user
            - name: NEXTCLOUD_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-secrets
                  key: nextcloud_admin_password
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: nextcloud-secrets
                  key: mysql_admin_user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-secrets
                  key: mysql_admin_password
            - name: MYSQL_DATABASE
              value: nextcloud
            - name: MYSQL_HOST
              value: mariadb
            {{- if .Values.redis.enabled }}
            - name: REDIS_HOST
              value: redis
            {{- end }}
            - name: TRUSTED_PROXIES
              value: {{ .Values.nextcloud.trusted_proxies }}
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              value: {{ .Values.nextcloud.host }}
            - name: OVERWRITEPROTOCOL
              value: https
            - name: TZ
              value: {{ .Values.timezone }}
          volumeMounts:
            - name: html
              mountPath: /var/www/html
            - name: config
              mountPath: /var/www/html/config
            - name: apps
              mountPath: /var/www/html/custom_apps
            - name: data
              mountPath: /var/www/html/data
      volumes:
        - name: html
          persistentVolumeClaim:
            claimName: nextcloud-html
        - name: config
          persistentVolumeClaim:
            claimName: nextcloud-config
        - name: apps
          persistentVolumeClaim:
            claimName: nextcloud-apps
        - name: data
          persistentVolumeClaim:
            claimName: nextcloud-data
