apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  mysql_root_password: {{ .Values.secrets.mysql_root_password }}
  mysql_admin_user: {{ .Values.secrets.mysql_admin_user }}
  mysql_admin_password: {{ .Values.secrets.mysql_admin_password }}
  nextcloud_admin_user: {{ .Values.secrets.nextcloud_admin_user }}
  nextcloud_admin_password: {{ .Values.secrets.nextcloud_admin_password }}
